/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businesscardholder;

/**
 *
 * @author kch79
 */
public class BusinessCardHolderForm extends javax.swing.JFrame {
    BusinessCardHolder businessCardHolder;
    /**
     * Creates new form BusinessCardHolderForm
     */
    public BusinessCardHolderForm() {
        //1. 윈도우가 생성될 때
        initComponents();
        //1.1. 명함첩을 생성하다.
        this.businessCardHolder=new BusinessCardHolder();
    }
    /*
    public void Load() {
        
    }
    public void Save() {
        
    }
    public void Insert(BusinessCard index){
        
    }
    public void Delete(BusinessCard index){
        
    }
    public String MakeCompanyCode(){
        
    }
    public String MakePersonalCode(){
        
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_NAME = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_ADDRESS = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_TELEPHONENUMBER = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_FAXNUMBER = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_URL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_NAME = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_TELEPHONENUMBER = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_EMAILADDRESS = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_POSITION = new javax.swing.JLabel();
        IDC_BUTTON_PUTIN = new javax.swing.JButton();
        IDC_BUTTON_FIND = new javax.swing.JButton();
        IDC_BUTTON_PUTOUT = new javax.swing.JButton();
        IDC_BUTTON_ARRANGE = new javax.swing.JButton();
        IDC_BUTTON_FIRST = new javax.swing.JButton();
        IDC_BUTTON_PREVIOUS = new javax.swing.JButton();
        IDC_BUTTON_NEXT = new javax.swing.JButton();
        IDC_BUTTON_LAST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("명함첩");
        setName("IDD_BUSINESSCARDHOLDERFORM"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setToolTipText("회사");

        jLabel1.setText("상호 : ");

        jLabel2.setText("주소 : ");

        jLabel3.setText("전화번호 : ");

        jLabel4.setText("팩스번호 : ");

        jLabel5.setText("홈페이지 : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDC_STATIC_COMPANY_ADDRESS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_TELEPHONENUMBER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_FAXNUMBER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_URL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDC_STATIC_COMPANY_NAME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDC_STATIC_COMPANY_ADDRESS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDC_STATIC_COMPANY_TELEPHONENUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDC_STATIC_COMPANY_FAXNUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IDC_STATIC_COMPANY_URL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setToolTipText("개인");

        jLabel6.setText("성명 : ");

        jLabel7.setText("전화번호 : ");

        jLabel8.setText("이메일주소 : ");

        jLabel9.setText("직책 : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDC_STATIC_PERSONAL_POSITION, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_PERSONAL_TELEPHONENUMBER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_PERSONAL_EMAILADDRESS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_PERSONAL_NAME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IDC_STATIC_PERSONAL_NAME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDC_STATIC_PERSONAL_TELEPHONENUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IDC_STATIC_PERSONAL_EMAILADDRESS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IDC_STATIC_PERSONAL_POSITION))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IDC_BUTTON_PUTIN.setText("끼우기");
        IDC_BUTTON_PUTIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_PUTINActionPerformed(evt);
            }
        });

        IDC_BUTTON_FIND.setText("찾기");
        IDC_BUTTON_FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_FINDActionPerformed(evt);
            }
        });

        IDC_BUTTON_PUTOUT.setText("들어내기");
        IDC_BUTTON_PUTOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_PUTOUTActionPerformed(evt);
            }
        });

        IDC_BUTTON_ARRANGE.setText("정리하기");
        IDC_BUTTON_ARRANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_ARRANGEActionPerformed(evt);
            }
        });

        IDC_BUTTON_FIRST.setText("처음");
        IDC_BUTTON_FIRST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_FIRSTActionPerformed(evt);
            }
        });

        IDC_BUTTON_PREVIOUS.setText("이전");
        IDC_BUTTON_PREVIOUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_PREVIOUSActionPerformed(evt);
            }
        });

        IDC_BUTTON_NEXT.setText("다음");
        IDC_BUTTON_NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_NEXTActionPerformed(evt);
            }
        });

        IDC_BUTTON_LAST.setText("마지막");
        IDC_BUTTON_LAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_LASTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDC_BUTTON_FIRST)
                        .addGap(75, 75, 75)
                        .addComponent(IDC_BUTTON_PREVIOUS)
                        .addGap(90, 90, 90)
                        .addComponent(IDC_BUTTON_NEXT)
                        .addGap(61, 61, 61)
                        .addComponent(IDC_BUTTON_LAST))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDC_BUTTON_PUTOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_BUTTON_ARRANGE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_BUTTON_FIND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_BUTTON_PUTIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(IDC_BUTTON_PUTIN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDC_BUTTON_FIND)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDC_BUTTON_PUTOUT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDC_BUTTON_ARRANGE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDC_BUTTON_PREVIOUS)
                    .addComponent(IDC_BUTTON_FIRST)
                    .addComponent(IDC_BUTTON_LAST)
                    .addComponent(IDC_BUTTON_NEXT))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDC_BUTTON_PUTINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_PUTINActionPerformed
        // TODO add your handling code here:
        //2. 끼우기 버튼을 클릭했을 때
        //2.1. 끼우기 윈도우를 출력한다.
        new PuttingInForm(this).setVisible(true);

    }//GEN-LAST:event_IDC_BUTTON_PUTINActionPerformed

    private void IDC_BUTTON_FINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_FINDActionPerformed
        // TODO add your handling code here:
        //3. 찾기 버튼을 클릭했을 때
        //3.1. 찾기 윈도우를 출력한다.
        new FindingForm(this).setVisible(true);
    }//GEN-LAST:event_IDC_BUTTON_FINDActionPerformed

    private void IDC_BUTTON_PUTOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_PUTOUTActionPerformed
        // TODO add your handling code here:
        //4. 들어내기 버튼을 클릭했을 때
        //4.1. 들어내기 윈도우를 출력한다.
        new PuttingOutForm(this).setVisible(true);
    }//GEN-LAST:event_IDC_BUTTON_PUTOUTActionPerformed

    private void IDC_BUTTON_ARRANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_ARRANGEActionPerformed
        // TODO add your handling code here:
        //5. 정리하기 버튼을 클릭했을 때
    }//GEN-LAST:event_IDC_BUTTON_ARRANGEActionPerformed

    private void IDC_BUTTON_FIRSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_FIRSTActionPerformed
        // TODO add your handling code here:
        //6. 처음 버튼을 클릭했을 때
        //6.1. 명함첩에서 처음으로 이동하다.
        BusinessCard index=this.businessCardHolder.First();
        //6.2. 명함을 출력하다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }//GEN-LAST:event_IDC_BUTTON_FIRSTActionPerformed

    private void IDC_BUTTON_PREVIOUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_PREVIOUSActionPerformed
        // TODO add your handling code here:
        //7. 이전 버튼을 클릭했을 때
        //7.1. 명함첩에서 이전으로 이동하다.
        BusinessCard index=this.businessCardHolder.Previous();
        //7.2. 명함을 출력하다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }//GEN-LAST:event_IDC_BUTTON_PREVIOUSActionPerformed

    private void IDC_BUTTON_NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_NEXTActionPerformed
        // TODO add your handling code here:
        //8. 다음 버튼을 클릭했을 때
        //8.1. 명함첩에서 다음으로 이동하다.
        BusinessCard index=this.businessCardHolder.Next();
        //8.2. 명함을 출력하다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }        
    }//GEN-LAST:event_IDC_BUTTON_NEXTActionPerformed

    private void IDC_BUTTON_LASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_LASTActionPerformed
        // TODO add your handling code here:
        //9. 마지막 버튼을 클릭했을 때
        //9.1. 명함첩에서 마지막으로 이동하다.
        BusinessCard index=this.businessCardHolder.Last();
        //9.2. 명함을 출력하다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }//GEN-LAST:event_IDC_BUTTON_LASTActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //10. 닫기 버튼을 클릭했을 때
        //10.1. 명함첩을 지우다.
        //10.2. 윈도우를 닫다.
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusinessCardHolderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusinessCardHolderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusinessCardHolderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusinessCardHolderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusinessCardHolderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDC_BUTTON_ARRANGE;
    private javax.swing.JButton IDC_BUTTON_FIND;
    private javax.swing.JButton IDC_BUTTON_FIRST;
    private javax.swing.JButton IDC_BUTTON_LAST;
    private javax.swing.JButton IDC_BUTTON_NEXT;
    private javax.swing.JButton IDC_BUTTON_PREVIOUS;
    private javax.swing.JButton IDC_BUTTON_PUTIN;
    private javax.swing.JButton IDC_BUTTON_PUTOUT;
    javax.swing.JLabel IDC_STATIC_COMPANY_ADDRESS;
    javax.swing.JLabel IDC_STATIC_COMPANY_FAXNUMBER;
    javax.swing.JLabel IDC_STATIC_COMPANY_NAME;
    javax.swing.JLabel IDC_STATIC_COMPANY_TELEPHONENUMBER;
    javax.swing.JLabel IDC_STATIC_COMPANY_URL;
    javax.swing.JLabel IDC_STATIC_PERSONAL_EMAILADDRESS;
    javax.swing.JLabel IDC_STATIC_PERSONAL_NAME;
    javax.swing.JLabel IDC_STATIC_PERSONAL_POSITION;
    javax.swing.JLabel IDC_STATIC_PERSONAL_TELEPHONENUMBER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
