/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businesscardholder;

/**
 *
 * @author kch79
 */
public class FindingForm extends javax.swing.JFrame {
    private BusinessCardHolderForm businessCardHolderForm;
    private BusinessCard[] indexes;
    private int current;
    /**
     * Creates new form FindingForm
     */
    public FindingForm(BusinessCardHolderForm businessCardHolderForm) {
        //찾기 윈도우가 생성될 때
        initComponents();
        this.indexes=null;
        this.current=-1;
        //명함첩 윈도우 연결 가능
        this.businessCardHolderForm=businessCardHolderForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDC_EDIT_NAME = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_NAME = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_ADDRESS = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_TELEPHONENUMBER = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_FAXNUMBER = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_URL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_NAME = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_TELEPHONENUMBER = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_EMAILADDRESS = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_POSITION = new javax.swing.JLabel();
        IDC_BUTTON_FIND = new javax.swing.JButton();
        IDC_BUTTON_SELECT = new javax.swing.JButton();
        IDC_BUTTON_FIRST = new javax.swing.JButton();
        IDC_BUTTON_PREVIOUS = new javax.swing.JButton();
        IDC_BUTTON_NEXT = new javax.swing.JButton();
        IDC_BUTTON_LAST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("성명 : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDC_EDIT_NAME)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDC_EDIT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setText("상호 : ");

        jLabel3.setText("주소 : ");

        jLabel4.setText("전화번호 : ");

        jLabel5.setText("팩스번호 : ");

        jLabel6.setText("홈페이지 : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDC_STATIC_COMPANY_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_ADDRESS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_TELEPHONENUMBER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_FAXNUMBER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDC_STATIC_COMPANY_URL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDC_STATIC_COMPANY_NAME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDC_STATIC_COMPANY_ADDRESS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDC_STATIC_COMPANY_TELEPHONENUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IDC_STATIC_COMPANY_FAXNUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IDC_STATIC_COMPANY_URL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("성명 : ");

        jLabel8.setText("전화번호 : ");

        jLabel9.setText("이메일주소 : ");

        jLabel10.setText("직책 : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDC_STATIC_PERSONAL_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_PERSONAL_TELEPHONENUMBER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_PERSONAL_EMAILADDRESS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_PERSONAL_POSITION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDC_STATIC_PERSONAL_NAME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IDC_STATIC_PERSONAL_TELEPHONENUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IDC_STATIC_PERSONAL_EMAILADDRESS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(IDC_STATIC_PERSONAL_POSITION))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IDC_BUTTON_FIND.setText("찾기");
        IDC_BUTTON_FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_FINDActionPerformed(evt);
            }
        });

        IDC_BUTTON_SELECT.setText("선택");
        IDC_BUTTON_SELECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_SELECTActionPerformed(evt);
            }
        });

        IDC_BUTTON_FIRST.setText("처음");
        IDC_BUTTON_FIRST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_FIRSTActionPerformed(evt);
            }
        });

        IDC_BUTTON_PREVIOUS.setText("이전");
        IDC_BUTTON_PREVIOUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_PREVIOUSActionPerformed(evt);
            }
        });

        IDC_BUTTON_NEXT.setText("다음");
        IDC_BUTTON_NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_NEXTActionPerformed(evt);
            }
        });

        IDC_BUTTON_LAST.setText("마지막");
        IDC_BUTTON_LAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_LASTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDC_BUTTON_FIRST)
                        .addGap(75, 75, 75)
                        .addComponent(IDC_BUTTON_PREVIOUS)
                        .addGap(79, 79, 79)
                        .addComponent(IDC_BUTTON_NEXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(IDC_BUTTON_LAST))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IDC_BUTTON_FIND, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(IDC_BUTTON_SELECT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDC_BUTTON_FIND)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDC_BUTTON_SELECT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDC_BUTTON_FIRST)
                    .addComponent(IDC_BUTTON_PREVIOUS)
                    .addComponent(IDC_BUTTON_NEXT)
                    .addComponent(IDC_BUTTON_LAST))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDC_BUTTON_FINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_FINDActionPerformed
        // TODO add your handling code here:
        //1. 찾기 버튼을 클릭했을 때
        //1.1. 성명을 입력받는다.
        String name=this.IDC_EDIT_NAME.getText();
        //1.2. 명함첩 윈도우를 찾는다.
        //1.3. 명함첩 윈도우의 명함첩에서 찾는다.
        this.indexes=this.businessCardHolderForm.businessCardHolder.Find(name);
        //1.4. 찾았으면 첫 번째 명함을 출력한다.
        if(this.indexes.length > 0){
            BusinessCard index=this.indexes[0];
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
            this.current=0;
        }
    }//GEN-LAST:event_IDC_BUTTON_FINDActionPerformed

    private void IDC_BUTTON_SELECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_SELECTActionPerformed
        // TODO add your handling code here:
        //2. 선택 버튼을 클릭했을 때
        //2.1. 선택된 명함의 위치를 읽는다.
        //2.2. 명함첩 윈도우를 찾는다.
        //2.3. 명함첩 윈도우의 명함첩에서 이동한다.
        BusinessCard index=this.businessCardHolderForm.businessCardHolder.Move(this.indexes[this.current]);
        //2.4. 명함첩 윈도우에 선택된 명함을 출력한다.
        this.businessCardHolderForm.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        //2.5. 찾기 윈도우를 닫는다.
        this.dispose();
    }//GEN-LAST:event_IDC_BUTTON_SELECTActionPerformed

    private void IDC_BUTTON_FIRSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_FIRSTActionPerformed
        // TODO add your handling code here:
        //3. 처음 버튼을 클릭했을 때
        //3.1. 처음 명함의 위치를 읽는다.
        this.current=0;
        BusinessCard index=this.indexes[this.current];
        //3.2. 명함을 출력한다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }//GEN-LAST:event_IDC_BUTTON_FIRSTActionPerformed

    private void IDC_BUTTON_PREVIOUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_PREVIOUSActionPerformed
        // TODO add your handling code here:
        //4. 이전 버튼을 클릭했을 때
        //4.1. 이전 명함의 위치를 읽는다.
        this.current--;
        if(this.current < 0){
            this.current=0;
        }
        BusinessCard index=this.indexes[this.current];
        //4.2. 명함을 출력한다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }//GEN-LAST:event_IDC_BUTTON_PREVIOUSActionPerformed

    private void IDC_BUTTON_NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_NEXTActionPerformed
        // TODO add your handling code here:
        //5. 다음 버튼을 클릭했을 때
        //5.1. 다음 명함의 위치를 읽는다.
        this.current++;
        if(this.current >= this.indexes.length){
            this.current=this.indexes.length-1;
        }
        BusinessCard index=this.indexes[this.current];
        //5.2. 명함을 출력한다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }//GEN-LAST:event_IDC_BUTTON_NEXTActionPerformed

    private void IDC_BUTTON_LASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_LASTActionPerformed
        // TODO add your handling code here:
        //6. 마지막 버튼을 클릭했을 때
        //6.1. 마지막 명함의 위치를 읽는다.
        this.current=this.indexes.length-1;
        BusinessCard index=this.indexes[this.current];
        //6.2. 명함을 출력한다.
        if(index != null){
            this.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        else{
            this.IDC_STATIC_COMPANY_NAME.setText("");
            this.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.IDC_STATIC_COMPANY_URL.setText("");
            this.IDC_STATIC_PERSONAL_NAME.setText("");
            this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }//GEN-LAST:event_IDC_BUTTON_LASTActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDC_BUTTON_FIND;
    private javax.swing.JButton IDC_BUTTON_FIRST;
    private javax.swing.JButton IDC_BUTTON_LAST;
    private javax.swing.JButton IDC_BUTTON_NEXT;
    private javax.swing.JButton IDC_BUTTON_PREVIOUS;
    private javax.swing.JButton IDC_BUTTON_SELECT;
    private javax.swing.JTextField IDC_EDIT_NAME;
    private javax.swing.JLabel IDC_STATIC_COMPANY_ADDRESS;
    private javax.swing.JLabel IDC_STATIC_COMPANY_FAXNUMBER;
    private javax.swing.JLabel IDC_STATIC_COMPANY_NAME;
    private javax.swing.JLabel IDC_STATIC_COMPANY_TELEPHONENUMBER;
    private javax.swing.JLabel IDC_STATIC_COMPANY_URL;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_EMAILADDRESS;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_NAME;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_POSITION;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_TELEPHONENUMBER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
