/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businesscardholder;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;

/**
 *
 * @author kch79
 */
public class PuttingOutForm extends javax.swing.JFrame {
    private BusinessCardHolderForm businessCardHolderForm;
    /**
     * Creates new form PuttingOutForm
     */
    public PuttingOutForm(BusinessCardHolderForm businessCardHolderForm) {
        //1. 들어내기 윈도우가 생성될 때
        initComponents();
        //명함첩 윈도우 연결 가능
        this.businessCardHolderForm=businessCardHolderForm;
        
        //1.1. 명함첩 윈도우를 찾는다.
        //1.2. 명함첩 윈도우의 명함첩에서 명함을 들어낸다.
        BusinessCard index=this.businessCardHolderForm.businessCardHolder.GetCurrent();
        BusinessCard businessCard=this.businessCardHolderForm.businessCardHolder.PutOut(index);
        //1.3. 들어내기 윈도우에 명함을 출력한다.
        this.IDC_STATIC_COMPANY_NAME.setText(businessCard.GetCompanyName());
        this.IDC_STATIC_COMPANY_ADDRESS.setText(businessCard.GetAddress());
        this.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(businessCard.GetCompanyTelephoneNumber());
        this.IDC_STATIC_COMPANY_FAXNUMBER.setText(businessCard.GetFaxNumber());
        this.IDC_STATIC_COMPANY_URL.setText(businessCard.GetUrl());
        this.IDC_STATIC_PERSONAL_NAME.setText(businessCard.GetPersonalName());
        this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(businessCard.GetPersonalTelephoneNumber());
        this.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(businessCard.GetEmailAddress());
        this.IDC_STATIC_PERSONAL_POSITION.setText(businessCard.GetPosition());
        //1.4. 명함첩 윈도우의 명함첩에 명함이 있으면 명함첩 윈도우에 명함을 출력한다.
        index=this.businessCardHolderForm.businessCardHolder.GetCurrent();
        if(index != null){
            this.businessCardHolderForm.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        }
        //1.5. 명함첩 윈도우의 명함첩에 명함이 없으면 명함첩 윈도우에 공란을 출력한다.
        else{
            this.businessCardHolderForm.IDC_STATIC_COMPANY_NAME.setText("");
            this.businessCardHolderForm.IDC_STATIC_COMPANY_ADDRESS.setText("");
            this.businessCardHolderForm.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText("");
            this.businessCardHolderForm.IDC_STATIC_COMPANY_FAXNUMBER.setText("");
            this.businessCardHolderForm.IDC_STATIC_COMPANY_URL.setText("");
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_NAME.setText("");
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText("");
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_EMAILADDRESS.setText("");
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_POSITION.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_ADDRESS = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_NAME = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_TELEPHONENUMBER = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_FAXNUMBER = new javax.swing.JLabel();
        IDC_STATIC_COMPANY_URL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_NAME = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_TELEPHONENUMBER = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_EMAILADDRESS = new javax.swing.JLabel();
        IDC_STATIC_PERSONAL_POSITION = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setText("상호 : ");

        jLabel3.setText("주소 : ");

        jLabel4.setText("전화번호 : ");

        jLabel5.setText("팩스번호 : ");

        jLabel6.setText("홈페이지 : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDC_STATIC_COMPANY_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_COMPANY_ADDRESS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_COMPANY_TELEPHONENUMBER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDC_STATIC_COMPANY_URL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDC_STATIC_COMPANY_FAXNUMBER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDC_STATIC_COMPANY_NAME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDC_STATIC_COMPANY_ADDRESS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDC_STATIC_COMPANY_TELEPHONENUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IDC_STATIC_COMPANY_FAXNUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IDC_STATIC_COMPANY_URL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("성명 : ");

        jLabel8.setText("전화번호 : ");

        jLabel9.setText("이메일주소 : ");

        jLabel10.setText("직책 : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDC_STATIC_PERSONAL_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_PERSONAL_TELEPHONENUMBER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_PERSONAL_EMAILADDRESS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDC_STATIC_PERSONAL_POSITION, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDC_STATIC_PERSONAL_NAME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IDC_STATIC_PERSONAL_TELEPHONENUMBER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IDC_STATIC_PERSONAL_EMAILADDRESS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(IDC_STATIC_PERSONAL_POSITION))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //2. 닫기 버튼을 클릭했을 때
        //2.1. 메세지 박스를 출력한다.
        int ret=JOptionPane.showConfirmDialog(null, "끼우시겠습니까?", "끼우기", YES_NO_CANCEL_OPTION);
        //2.2. 예 버튼을 클릭했을 때
        if(ret==JOptionPane.YES_OPTION){        
            String companyName=this.IDC_STATIC_COMPANY_NAME.getText();
            String address=this.IDC_STATIC_COMPANY_ADDRESS.getText();
            String companyTelephoneNumber=this.IDC_STATIC_COMPANY_TELEPHONENUMBER.getText();
            String faxNumber=this.IDC_STATIC_COMPANY_FAXNUMBER.getText();
            String url=this.IDC_STATIC_COMPANY_URL.getText();
            String personalName=this.IDC_STATIC_PERSONAL_NAME.getText();
            String personalTelephoneNumber=this.IDC_STATIC_PERSONAL_TELEPHONENUMBER.getText();
            String emailAddress=this.IDC_STATIC_PERSONAL_EMAILADDRESS.getText();
            String position=this.IDC_STATIC_PERSONAL_POSITION.getText();
            BusinessCard businessCard=new BusinessCard(companyName, address, companyTelephoneNumber, faxNumber, url, 
                    personalName, personalTelephoneNumber, emailAddress, position);
            //2.2.1. 명함첩 윈도우를 찾는다.
            //2.2.2. 명함첩 윈도우의 명함첩에 끼운다.
            BusinessCard index=this.businessCardHolderForm.businessCardHolder.PutIn(businessCard);
            //2.2.3. 명함첩 윈도우에 명함을 출력하다.
            this.businessCardHolderForm.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.businessCardHolderForm.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
            this.businessCardHolderForm.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
            //2.2.4. 들어내기 윈도우를 닫는다.
            this.dispose();
        }
        //2.3. 아니오 버튼을 클릭했을 때
        else if(ret==JOptionPane.NO_OPTION){
            //2.3.1. 들어내기 윈도우를 닫는다.
            this.dispose();
        }else if(ret==JOptionPane.CANCEL_OPTION){
            
        }
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDC_STATIC_COMPANY_ADDRESS;
    private javax.swing.JLabel IDC_STATIC_COMPANY_FAXNUMBER;
    private javax.swing.JLabel IDC_STATIC_COMPANY_NAME;
    private javax.swing.JLabel IDC_STATIC_COMPANY_TELEPHONENUMBER;
    private javax.swing.JLabel IDC_STATIC_COMPANY_URL;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_EMAILADDRESS;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_NAME;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_POSITION;
    private javax.swing.JLabel IDC_STATIC_PERSONAL_TELEPHONENUMBER;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
