/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package businesscardholder;

/**
 *
 * @author kch79
 */
public class PuttingInForm extends javax.swing.JFrame {
    private BusinessCardHolderForm businessCardHolderForm;
    /**
     * Creates new form PuttingInForm
     */
    public PuttingInForm(BusinessCardHolderForm businessCardHolderForm) {
        //1. 끼우기 윈도우가 생성될 때
        initComponents();
        //명함첩 윈도우 연결 가능
        this.businessCardHolderForm=businessCardHolderForm;
        //1.1. 도메인 목록을 만든다.
        //1.2. 직책 목록을 만든다.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDC_EDIT_COMPANY_NAME = new javax.swing.JTextField();
        IDC_EDIT_COMPANY_ADDRESS = new javax.swing.JTextField();
        IDC_EDIT_COMPANY_TELEPHONENUMBER = new javax.swing.JTextField();
        IDC_EDIT_COMPANY_FAXNUMBER = new javax.swing.JTextField();
        IDC_EDIT_COMPANY_URL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IDC_EDIT_PERSONAL_NAME = new javax.swing.JTextField();
        IDC_EDIT_PERSONAL_TELEPHONENUMBER = new javax.swing.JTextField();
        IDC_EDIT_PERSONAL_EMAILID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        IDC_COMBO_DOMAIN = new javax.swing.JComboBox<>();
        IDC_COMBO_POSITION = new javax.swing.JComboBox<>();
        IDC_BUTTON_PUTIN = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("상호 : ");

        jLabel2.setText("주소 : ");

        jLabel3.setText("전화번호 : ");

        jLabel4.setText("팩스번호 : ");

        jLabel5.setText("홈페이지 : ");

        IDC_EDIT_COMPANY_NAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDC_EDIT_COMPANY_NAMEFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDC_EDIT_COMPANY_NAME)
                    .addComponent(IDC_EDIT_COMPANY_ADDRESS)
                    .addComponent(IDC_EDIT_COMPANY_TELEPHONENUMBER)
                    .addComponent(IDC_EDIT_COMPANY_FAXNUMBER)
                    .addComponent(IDC_EDIT_COMPANY_URL))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDC_EDIT_COMPANY_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDC_EDIT_COMPANY_ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IDC_EDIT_COMPANY_TELEPHONENUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDC_EDIT_COMPANY_FAXNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IDC_EDIT_COMPANY_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel6.setText("성명 : ");

        jLabel7.setText("전화번호 : ");

        jLabel8.setText("이메일주소 : ");

        jLabel9.setText("직책 : ");

        jLabel10.setText("@");

        IDC_COMBO_DOMAIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "naver.com", "gmail.com", "daum.net", "nate.com" }));
        IDC_COMBO_DOMAIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_COMBO_DOMAINActionPerformed(evt);
            }
        });

        IDC_COMBO_POSITION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "사원", "주임", "대리", "차장", "부장", "사장", "회장" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDC_EDIT_PERSONAL_NAME)
                            .addComponent(IDC_EDIT_PERSONAL_TELEPHONENUMBER)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(IDC_COMBO_POSITION, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(IDC_EDIT_PERSONAL_EMAILID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDC_COMBO_DOMAIN, 0, 128, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IDC_EDIT_PERSONAL_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IDC_EDIT_PERSONAL_TELEPHONENUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDC_COMBO_DOMAIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(IDC_EDIT_PERSONAL_EMAILID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IDC_COMBO_POSITION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        IDC_BUTTON_PUTIN.setText("끼우기");
        IDC_BUTTON_PUTIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_PUTINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDC_BUTTON_PUTIN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(IDC_BUTTON_PUTIN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDC_COMBO_DOMAINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_COMBO_DOMAINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDC_COMBO_DOMAINActionPerformed

    private void IDC_EDIT_COMPANY_NAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDC_EDIT_COMPANY_NAMEFocusLost
        // TODO add your handling code here:
        //2. 상호 에딧의 포커스를 읽었을 때
        //2.1. 상호를 읽는다.
        String companyName=IDC_EDIT_COMPANY_NAME.getText();
        //2.2. 명함첩 윈도우를 찾는다.
        //2.3. 명함첩 윈도우의 명함첩에서 찾는다.
        BusinessCard index=this.businessCardHolderForm.businessCardHolder.FindByCompanyName(companyName);
        //2.4. 찾았으면 회사를 출력한다.
        if(index != null){
            this.IDC_EDIT_COMPANY_NAME.setText(index.GetCompanyName());
            this.IDC_EDIT_COMPANY_ADDRESS.setText(index.GetAddress());
            this.IDC_EDIT_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
            this.IDC_EDIT_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
            this.IDC_EDIT_COMPANY_URL.setText(index.GetUrl());
        }
        
    }//GEN-LAST:event_IDC_EDIT_COMPANY_NAMEFocusLost

    private void IDC_BUTTON_PUTINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_PUTINActionPerformed
        // TODO add your handling code here:
        //3. 끼우기 버튼을 클릭했을 때
        //3.1. 명함을 읽는다.
        String companyName=this.IDC_EDIT_COMPANY_NAME.getText();
        String address=this.IDC_EDIT_COMPANY_ADDRESS.getText();
        String companyTelephoneNumber=this.IDC_EDIT_COMPANY_TELEPHONENUMBER.getText();
        String faxNumber=this.IDC_EDIT_COMPANY_FAXNUMBER.getText();
        String url=this.IDC_EDIT_COMPANY_URL.getText();
        String personalName=this.IDC_EDIT_PERSONAL_NAME.getText();
        String personalTelephoneNumber=this.IDC_EDIT_PERSONAL_TELEPHONENUMBER.getText();
        String emailId=this.IDC_EDIT_PERSONAL_EMAILID.getText();
        String domain=(String)this.IDC_COMBO_DOMAIN.getSelectedItem();
        String emailAddress=String.format("%s@%s", emailId, domain);
        String position=(String)this.IDC_COMBO_POSITION.getSelectedItem();
        BusinessCard businessCard=new BusinessCard(companyName, address, companyTelephoneNumber, faxNumber, url, 
                personalName, personalTelephoneNumber, emailAddress, position);
        //3.2. 명함첩 윈도우를 찾는다.
        //3.3. 명함첩 윈도우의 명함첩에 끼운다.
        BusinessCard index=this.businessCardHolderForm.businessCardHolder.PutIn(businessCard);
        //3.4. 명함첩 윈도우에 명함을 출력한다.
        this.businessCardHolderForm.IDC_STATIC_COMPANY_NAME.setText(index.GetCompanyName());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_ADDRESS.setText(index.GetAddress());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_TELEPHONENUMBER.setText(index.GetCompanyTelephoneNumber());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_FAXNUMBER.setText(index.GetFaxNumber());
        this.businessCardHolderForm.IDC_STATIC_COMPANY_URL.setText(index.GetUrl());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_NAME.setText(index.GetPersonalName());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_TELEPHONENUMBER.setText(index.GetPersonalTelephoneNumber());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_EMAILADDRESS.setText(index.GetEmailAddress());
        this.businessCardHolderForm.IDC_STATIC_PERSONAL_POSITION.setText(index.GetPosition());
        //3.5. 끼우기 윈도우를 닫는다.
        this.dispose();
    }//GEN-LAST:event_IDC_BUTTON_PUTINActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDC_BUTTON_PUTIN;
    private javax.swing.JComboBox<String> IDC_COMBO_DOMAIN;
    private javax.swing.JComboBox<String> IDC_COMBO_POSITION;
    private javax.swing.JTextField IDC_EDIT_COMPANY_ADDRESS;
    private javax.swing.JTextField IDC_EDIT_COMPANY_FAXNUMBER;
    private javax.swing.JTextField IDC_EDIT_COMPANY_NAME;
    private javax.swing.JTextField IDC_EDIT_COMPANY_TELEPHONENUMBER;
    private javax.swing.JTextField IDC_EDIT_COMPANY_URL;
    private javax.swing.JTextField IDC_EDIT_PERSONAL_EMAILID;
    private javax.swing.JTextField IDC_EDIT_PERSONAL_NAME;
    private javax.swing.JTextField IDC_EDIT_PERSONAL_TELEPHONENUMBER;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
