/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addressbook;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Taehoo
 */
public class FindingForm extends javax.swing.JFrame {
    UpdatingForm updatingForm;
    int []indexes;
    int count;
    /**
     * Creates new form FINDINGFORM
     */
    public FindingForm(UpdatingForm updatingForm) {
        initComponents();
        this.updatingForm = updatingForm;
        this.indexes = null;
        this.count =0;
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDC_BUTTON_FIND = new javax.swing.JButton();
        IDC_STATIC_NAME = new javax.swing.JLabel();
        IDC_EDIT_NAME = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Personals = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(672, 400));
        setSize(new java.awt.Dimension(400, 400));

        jLabel1.setText("찾기");

        IDC_BUTTON_FIND.setText("찾기");
        IDC_BUTTON_FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDC_BUTTON_FINDActionPerformed(evt);
            }
        });

        IDC_STATIC_NAME.setText("성명");

        Table_Personals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "번호", "성명", "주소", "전화번호", "이메일주소"
            }
        ));
        Table_Personals.setCellSelectionEnabled(true);
        Table_Personals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_PersonalsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Personals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(IDC_STATIC_NAME)
                        .addGap(45, 45, 45)
                        .addComponent(IDC_EDIT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(IDC_BUTTON_FIND, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDC_STATIC_NAME)
                    .addComponent(IDC_EDIT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDC_BUTTON_FIND))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDC_BUTTON_FINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDC_BUTTON_FINDActionPerformed
        String name;
        DefaultTableModel model = (DefaultTableModel)Table_Personals.getModel();
        Personal personal;
        String number;
        int i=0;
        name = IDC_EDIT_NAME.getText();//2.1. 성명을 읽다
        //2.2. 주소록 윈도우를 찾다.
        
        if(indexes != null){
            indexes = null;
        }
        this.indexes = this.updatingForm.addressBook.Find(name);//2.3. 주소록윈도우의 주소록에서 찾다.
        model.setRowCount(0);//2.4. 리스트뷰의 모든항목을 지우다.
       
        while(i<indexes.length){//2.5. 리스트뷰 컨트롤에서 찾은 수만큼 항목을 추가하다.
            personal = this.updatingForm.addressBook.GetAt(indexes[i]);
            number = Integer.toString(i+1);
            model.addRow(new Object[] { number, personal.GetName(), personal.GetAddress(),
                personal.GetTelephoneNumber(), personal.GetEmailAddress()});
            i++;
        }
    }//GEN-LAST:event_IDC_BUTTON_FINDActionPerformed

    private void Table_PersonalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_PersonalsMouseClicked
        int index;
        
        index = Table_Personals.getSelectedRow();
        String name = (String)Table_Personals.getValueAt(index, 1);
        String address = (String)Table_Personals.getValueAt(index, 2);
        String telephoneNumber = (String)Table_Personals.getValueAt(index, 3);
        String emailAddress = (String)Table_Personals.getValueAt(index ,4);
        
  
        this.updatingForm.Text_Name.setText(name);
        this.updatingForm.Text_Address.setText(address);
        this.updatingForm.Text_TelephoneNumber.setText(telephoneNumber);
        this.updatingForm.Text_EmailAddress.setText(emailAddress);
        this.updatingForm.Table_Personals.changeSelection(indexes[index], indexes[index], false, false);
        
       
        this.dispose();
    }//GEN-LAST:event_Table_PersonalsMouseClicked

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDC_BUTTON_FIND;
    private javax.swing.JTextField IDC_EDIT_NAME;
    private javax.swing.JLabel IDC_STATIC_NAME;
    javax.swing.JTable Table_Personals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
